### ISSUE TITLE
Al guardar un Flujo de Publicación que esta creado correctamente, se genera error

### ISSUE THREAD

**Issue by jordivs** [SemanticWebBuilder/SWBPortal#1]
Una vez que el Flujo de publicación se da guardar, la consola genera el siguiente error:

2017-01-02 15:47:49,112 ERROR -
java.lang.IllegalStateException: getWriter() ya ha sido llamado para esta respuesta
at org.apache.catalina.connector.Response.getOutputStream(Response.java:576)
at org.apache.catalina.connector.ResponseFacade.getOutputStream(ResponseFacade.java:194)
at org.semanticwb.servlet.SWBVirtualHostFilter.processError(SWBVirtualHostFilter.java:715)
at org.semanticwb.servlet.SWBVirtualHostFilter.processInternalServlet(SWBVirtualHostFilter.java:415)
at org.semanticwb.servlet.SWBVirtualHostFilter.doFilter(SWBVirtualHostFilter.java:334)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1452)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:745)

**Comment by haxdai** [comment]
@jordivs Lo probé con el código de los repositorios de github. Tienes más información? Navegador?

**Comment by jordivs** [comment]
Se crea un flujo de publicación con el siguiente procedimiento:
1.- Se crea flujo desde el árbol del sitio 
2.- Se define el recurso
3.- Se definen 2 actividades 
4.- Se realiza la secuencia correspondiente a las actividades
5.- se da "Guardar flujo"

Resultado:
Se genera un cuadro de dialogo con la leyenda "Ha ocurrido un error"

Ambiente:
Sistema Operativo: CentOS 7
Navegador: Mozila FireFox 45.4.0
Base de Datos: Hipersonic
Servidor de Aplicaciones: Tomcat 9
Versión Java: 1.8
Versión SWB: 4.5.11.2
