### ISSUE TITLE
Reporte de accesos por canal no se genera correctamente

### ISSUE THREAD

**Issue by jordivs** [SemanticWebBuilder/SWBPortal#49]
<p>El reporte de accesos por canal no se generá y manda la siguiente exepción.</p>

<p>Exception in thread "Thread-43" java.lang.NullPointerException<br/>
        at org.semanticwb.portal.admin.resources.reports.PortalTree.insert(WBAChannelReport.java:831)<br/>
        at org.semanticwb.portal.admin.resources.reports.ChannelReportGenerator.getUnknownResults(WBAChannelReport.java:1033)<br/>
        at org.semanticwb.portal.admin.resources.reports.ChannelReportGenerator.run(WBAChannelReport<br/>
.java:1060)</p>

## Affects versions
* 4.2.2.0

## Fix versions
* 4.5.0.0

## Environment
<p>Browser: Chrome<br/>
AppServer: Tomcat 7</p>

## Kenai Metadata

|created|updated|reporter|assignee|due|resolved|link|
|---|---|---|---|---|---|---|
|Wed, 5 Dec 2012 00:09:53 +0000|Wed, 9 Oct 2013 23:47:46 +0000|jordi|carlos.ramos|Tue, 4 Dec 2012 00:00:00 +0000|Wed, 9 Oct 2013 23:47:46 +0000|[https://kenai.com/jira/browse/SEMANTICWEBBUILDER-73](https://kenai.com/jira/browse/SEMANTICWEBBUILDER-73)|

**Comment by jordivs** [comment]
<p>Ya no se genera el error</p>

## Kenai Metadata

|author|created|
|---|---|
|jordi|Wed, 9 Oct 2013 23:47:46 +0000|
