### ISSUE TITLE
Error en  el recurso Comment

### ISSUE THREAD

**Issue by jordivs** [SemanticWebBuilder/SWBPortal#62]
<p>Al llenar los campos del recurso Comment y enviar los datos para generar el contenido, este recurso no hace ninguna acción.</p>

<p>Pasos para replicar el Bug:<br/>
1.- En la administración de SWB dar de alta el recurso de Comment en una página web y configurar los datos requeridos de la administración del recurso<br/>
2.- Visualizar la página web en la salida HTML<br/>
3.- Llenar los datos solicitados incluyendo Capcha<br/>
4.- Dar clic en el botón de "Enviar"</p>

<p>El recurso tarda varios segundos en enviar los datos se recarga la página y el formulario del recurso desaparece de la página web sin ninguna ventana de aviso direccionando a la siguiente ruta</p>

<p>/_rid/12/_act/add?failure=Error%20al%20tratar%20de%20enviar%20el%20comentario.</p>

<p>y se genera un fallo al tratar de enviar el correo:</p>

<p>2014-09-18 11:29:43,939 ERROR -<br/>
org.apache.commons.mail.EmailException: Sending the email to the following serve<br/>
r failed : smtp.gmail.com:465<br/>
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1138)<br/>
        at org.apache.commons.mail.Email.send(Email.java:1163)<br/>
        at org.semanticwb.SWBUtils$EMAIL.sendMail(SWBUtils.java:3811)<br/>
        at org.semanticwb.portal.resources.Comment.processEmails(Comment.java:78<br/>
7)<br/>
        at org.semanticwb.portal.resources.Comment.processAction(Comment.java:15<br/>
2)<br/>
        at org.semanticwb.servlet.internal.Distributor._doProcess(Distributor.ja<br/>
va:374)<br/>
        at org.semanticwb.servlet.internal.Distributor.doProcess(Distributor.jav<br/>
a:101)<br/>
        at org.semanticwb.servlet.SWBVirtualHostFilter.processInternalServlet(SW<br/>
BVirtualHostFilter.java:407)<br/>
        at org.semanticwb.servlet.SWBVirtualHostFilter.doFilter(SWBVirtualHostFi<br/>
lter.java:334)<br/>
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl<br/>
icationFilterChain.java:239)<br/>
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF<br/>
ilterChain.java:206)<br/>
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperV<br/>
alve.java:219)<br/>
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextV<br/>
alve.java:106)<br/>
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(Authentica<br/>
torBase.java:504)<br/>
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.j<br/>
ava:142)<br/>
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.j<br/>
ava:79)<br/>
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAcce<br/>
ssLogValve.java:610)<br/>
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineVal<br/>
ve.java:88)<br/>
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.jav<br/>
a:534)<br/>
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp<br/>
11Processor.java:1081)<br/>
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(<br/>
AbstractProtocol.java:658)<br/>
        at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.pr<br/>
ocess(Http11AprProtocol.java:277)<br/>
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpo<br/>
int.java:2381)<br/>
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoin<br/>
t.java:2370)<br/>
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.<br/>
java:1145)<br/>
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor<br/>
.java:615)<br/>
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskTh<br/>
read.java:61)<br/>
        at java.lang.Thread.run(Thread.java:745)<br/>
Caused by: javax.mail.SendFailedException: Sending failed;<br/>
  nested exception is:<br/>
        class javax.mail.MessagingException: 530-5.5.1 Authentication Required.<br/>
Learn more at<br/>
530 5.5.1 <a href="http://support.google.com/mail/bin/answer.py?answer=14257" class="external-link" rel="nofollow">http://support.google.com/mail/bin/answer.py?answer=14257</a> cb9sm2596059<br/>
obb.18 - gsmtp</p>

<p>        at javax.mail.Transport.send0(Transport.java:218)<br/>
        at javax.mail.Transport.send(Transport.java:80)<br/>
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1128)<br/>
        ... 27 more</p>

## Affects versions
* 4.5.6.0
* 4.5.10.1

## Fix versions
* 4.5.10.1

## Environment
<p>MV<br/>
OS:Windows 8<br/>
AS:Tomcat 8.0.9<br/>
DB:Hipersonyc<br/>
Browser: GoogleChrome</p>

## Kenai Metadata

|created|updated|reporter|assignee|due|link|
|---|---|---|---|---|---|
|Tue, 8 Jul 2014 23:42:29 +0000|Thu, 18 Jun 2015 21:31:51 +0000|jordi|carlos.ramos||[https://kenai.com/jira/browse/SEMANTICWEBBUILDER-130](https://kenai.com/jira/browse/SEMANTICWEBBUILDER-130)|

**Comment by jordivs** [comment]
<p>El error persiste en la versión 4.5.10.1<br/>
.</p>

## Kenai Metadata

|author|created|
|---|---|
|jordi|Thu, 18 Jun 2015 21:30:52 +0000|

**Comment by jordivs** [comment]
<p>Se actualizo la incidencia y esta todavía persiste en el release 4.5.6.0</p>

## Kenai Metadata

|author|created|
|---|---|
|jordi|Thu, 18 Sep 2014 16:37:03 +0000|

**Comment by jordivs** [comment]
<p>Esta incidencia no ha sido atendida</p>

## Kenai Metadata

|author|created|
|---|---|
|jordi|Thu, 9 Oct 2014 16:02:46 +0000|

**Comment by jordivs** [comment]
<p>Favor de revisar este incidente Calos</p>

## Kenai Metadata

|author|created|
|---|---|
|vlorenzana|Wed, 9 Jul 2014 15:38:25 +0000|

**Comment by jordivs** [comment]
En la versión de pruebas de no-applets, ya no sucede el issue
